### PR TITLE
DSNS-234: New integration test that demonstrates dea scene select

### PR DESCRIPTION
**Pull request by gordonyeong**
DSNS-234: New integration test that demonstrates dea scene select
    will filter out scenes that haven't any ancillary data
    Req 2.4 Filter out if no ancillary

### CODE REVIEW

**Review by dunkgray — CHANGES_REQUESTED** [review]
Looks good.
update the function name;
test_ard_landsat_scenes_outside_AOI_r2_3

Plus lets remove the 'name' from the module names of
test_scene_name_filtering_outside_AOI_r_2_3.py
test_scene_name_no_ancillary_r_2_4.py

**Comment by gordonyeong** [comment]
will do so :)

**Comment by gordonyeong** [comment]
sorted.

**Review by dunkgray — APPROVED** [review]
Approved this PR
could 'name' be removed from this file too - test_scene_name_filtering_outside_AOI_r_2_3.py - for the next PR

**Pull request merged**
