### PR TITLE
DSNS-177: ard reprocessing l1s tests with fixtures

### PR DESCRIPTION
**Pull request by gordonyeong**
DSNS-177:
        - New tests: Rewrite of the ARD reprocessing test for level 1 data
            with fixtures. This will enable us to have test data added into
            a test database instance and destroyed by the end of the tests.
            This guarantees our tests to test the same data in a controlled
            manner every single time. These tests are the direct parallels of
            go_test_ard_reprocessed_l1s.sh and test_ard_reprocessed_l1s.py
            (which are retired as part of this exercise).
        - Maintenance: Removed unused argument in ard_reprocessed_l1s's ard_reprocessed_l1s()

### CODE REVIEW

**Review by dunkgray — COMMENTED** [review]
Thanks Gordon, this is looking good.
I'll do a PR onto this branch that's focused on simplifying things,  changing constant names to make it easier understand and removing some complex aspects of the original tests in master.

https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/58

**Review by dunkgray — APPROVED** [review]
We got there in the end.

**Review by dunkgray — APPROVED** [review]
Looks good

**Comment by gordonyeong** [comment]
thank you, Duncan :)

**Pull request merged**
